### ISSUE TITLE
js的评分实现

### ISSUE THREAD

**Issue by monic-shixi** [monic-shixi/my-babel#10]
```js
function rater(rate) {
  return "★★★★★☆☆☆☆☆".slice(5 - rate,10 - rate);
}
rater(4)
```

emmmm，这也是个法子，还有其他什么好的方式吗？

**Comment by monic-shixi** [comment]
这里也有一个，看起来还不错，这个是怎么搞得呢？

就是通过覆盖来实现：

https://codepen.io/weixun/pen/peQmqw

```html
 <div class="star-rating">
        <div class="star-rating-top" style="width:50%">
            <span>★</span>
            <span>★</span>
            <span>★</span>
            <span>★</span>
            <span>★</span>
        </div>
        <div class="star-rating-bottom">
            <span>★</span>
            <span>★</span>
            <span>★</span>
            <span>★</span>
            <span>★</span>
        </div>
    </div>
```

```css
.star-rating {
        unicode-bidi: bidi-override;
        color: #ddd;
        font-size: 0;
        height: 25px;
        margin: 0 auto;
        position: relative;
        display: table;
        padding: 0;
        text-shadow: 0px 1px 0 #a2a2a2;
    }

    .star-rating span {
        padding: 5px;
        font-size: 20px;
    }

    .star-rating-top {
        color: #FFD700;
        padding: 0;
        position: absolute;
        z-index: 1;
        display: block;
        top: 0;
        left: 0;
        overflow: hidden;
        white-space: nowrap;
    }

    .star-rating-bottom {
        padding: 0;
        display: block;
        z-index: 0;
    }
```
