### ISSUE TITLE
盒子模型

### ISSUE THREAD

**Issue by monic-shixi** [monic-shixi/my-babel#2]
盒模型主要有IE模型和标准模型。
css控制盒模型可以使用`box-sizing`属性。

- border-box
```css
box-sizing: border-box;
```
`border-box`这个是设置为 **IE盒模型** ，即设定的宽度是为`padding + border + content + border + padding`。

比如如下：
```css
div.border-box {
  border: 5px solod red;
  padding: 15px;
  width: 200px;
}
```
那么这个div的宽度就是200像素(包含了padding，border, content)。
```css
/* 总宽度: 200px
     盒内容宽度: 200px - (2 * 15px) - (2 * 5px) = 160px */
```

- content-box

然而还有一个`content-box`，这个是默认的值，**表示为w3c标准盒模型** 。你设置的宽度为内容宽度,所以盒子的实际宽度得是你设置的内容宽度再加上(padding + border)，也就是(padding + border + content + border + padding)。

比如如下：
```css
div.content-box {
  border: 5px solod red;
  padding: 15px;
  width: 200px;
}
```
那么这个div的宽度就是200像素，实际上是内容的宽度，并非实际宽度。
```css
/* 总宽度: 200px + 2*15px + 2*5px = 240px
     盒内容宽度: 200px */
```

具体信息可以参考：
[box-sizing](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing)
